### ISSUE TITLE
Refactor 

### ISSUE THREAD

**Issue by NateFerrell** [UMM-CSci-3601-S24/iteration-2-team-mahogany#3]
Bringing the up to speed, while looking at older issues from iteration 1, and possibly fixing and updating some old code.

**Comment by NicMcPhee** [comment]
This is a super vague issue. How do we know when this is _done_ and can be closed? This is the kind of issue that can easily balloon out and start to capture all kinds of other, unrelated work, making it a dangerous beast.

**Comment by NateFerrell** [comment]
This was handled, as it has now split into two separate issues, this is now Edit Task, along with split host controller.
